[package]
name = "rbxmath/fast-fourier-transform"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MPL-2.0"
authors = ["Aidan Epperly"]

[dependencies]
Scalars = "rbxmath/scalars@0.1.0"
Tools = "rbxmath/tools@0.1.0"
Primes = "rbxmath/primes@0.1.0"
